#!/usr/bin/env node
/**
 * fix-orphans.js — Generates interpolations for pre-existing orphans in eco.json.
 *
 * Reads output/foundOrphans.json (generated by `generatePullRequest.js --apply`),
 * processes entries with added:false (pre-existing orphans from eco*.json),
 * runs lineOfDescent for each, and patches output/toMerge/eco_interpolated.json.
 *
 * Also writes output/orphanFixes.json summarising what was done.
 *
 * Usage:
 *   node scripts/fix-orphans.js
 *
 * Must be run after: node generatePullRequest.js --apply --yes
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { ChessPGN } from "@chess-pgn/chess-pgn";
import { lineOfDescent } from "../steps/interpolations.js";
import { book } from "../utils.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const OUTPUT = path.resolve(ROOT, "output");
const TO_MERGE = path.resolve(OUTPUT, "toMerge");

const chess = new ChessPGN();

const loadJson = (p) => JSON.parse(fs.readFileSync(p, "utf8"));
const writeJson = (p, data) => fs.writeFileSync(p, JSON.stringify(data, null, 2));

// ── Guards ───────────────────────────────────────────────────────────────────

const orphansPath = path.join(OUTPUT, "foundOrphans.json");
const toMergeInterp = path.join(TO_MERGE, "eco_interpolated.json");

if (!fs.existsSync(orphansPath)) {
  console.error("ERROR: output/foundOrphans.json not found. Run `generatePullRequest.js --apply` first.");
  process.exit(1);
}
if (!fs.existsSync(toMergeInterp)) {
  console.error("ERROR: output/toMerge/eco_interpolated.json not found. Run `generatePullRequest.js --apply` first.");
  process.exit(1);
}

// ── Load data ────────────────────────────────────────────────────────────────

const allOrphans = loadJson(orphansPath);
const preExisting = allOrphans.filter((o) => o.added === false);
console.log(`Processing ${preExisting.length} pre-existing orphans (${allOrphans.length - preExisting.length} new-addition orphans skipped).\n`);

const interpolated = loadJson(toMergeInterp);
const allPositions = new Set([
  ...Object.keys(book).map((f) => f.split(" ")[0]),
  ...Object.keys(interpolated).map((f) => f.split(" ")[0]),
]);

// ── Process each orphan ───────────────────────────────────────────────────────

const newInterpolations = {};
const summary = [];
let skipped = 0;

for (const orphan of preExisting) {
  // Build a pseudo-added object so lineOfDescent can look up the entry
  const pseudoAdded = { [orphan.fen]: { ...orphan } };
  delete pseudoAdded[orphan.fen].added; // strip fix-orphans-only field

  let lod;
  try {
    lod = lineOfDescent(orphan.fen, pseudoAdded);
  } catch (e) {
    console.warn(`  WARN: lineOfDescent failed for ${orphan.name}: ${e.message}`);
    skipped++;
    continue;
  }

  // lod = [orphan, ...interpolated_bridges..., named_parent]
  // We want entries [1..n-1] (bridges only)
  const parent = lod[lod.length - 1];
  const bridges = lod.slice(1, -1).filter((e) => e.src === "interpolated");

  if (bridges.length === 0) {
    console.log(`  OK: ${orphan.name} — parent found directly (no bridges needed)`);
    summary.push({ orphan: orphan.name, moves: orphan.moves, bridgesAdded: 0, parent: parent.name, parentSrc: parent.src });
    continue;
  }

  // Set name and rootSrc on each bridge (lineOfDescent leaves them as 'TBD')
  for (const bridge of bridges) {
    bridge.name = parent.name + " (i)";
    bridge.rootSrc = parent.src;
  }

  let added = 0;
  let collisions = 0;
  for (const bridge of bridges) {
    // Get the FEN from moves
    try {
      chess.loadPgn(bridge.moves);
      const fen = chess.fen();
      const pos = fen.split(" ")[0];
      if (allPositions.has(pos)) {
        collisions++;
      } else {
        newInterpolations[fen] = { ...bridge, fen };
        allPositions.add(pos);
        added++;
      }
    } catch (e) {
      console.warn(`  WARN: could not resolve FEN for bridge "${bridge.moves}": ${e.message}`);
    }
  }

  console.log(`  ${orphan.name}: +${added} bridge(s)${collisions > 0 ? `, ${collisions} skipped (already exists)` : ""} → parent: ${parent.name}`);
  summary.push({
    orphan: orphan.name,
    moves: orphan.moves,
    bridgesAdded: added,
    bridgesSkipped: collisions,
    parent: parent.name,
    parentSrc: parent.src,
  });
}

// ── Apply and write ──────────────────────────────────────────────────────────

const newCount = Object.keys(newInterpolations).length;
if (newCount > 0) {
  Object.assign(interpolated, newInterpolations);
  writeJson(toMergeInterp, interpolated);
  console.log(`\n✓ ${newCount} new interpolation(s) written to output/toMerge/eco_interpolated.json`);
} else {
  console.log(`\n✓ No new interpolations needed.`);
}

writeJson(path.join(OUTPUT, "orphanFixes.json"), {
  generatedAt: new Date().toISOString(),
  preExistingOrphans: preExisting.length,
  newInterpolationsAdded: newCount,
  skipped,
  fixes: summary,
});
console.log(`✓ Summary written to output/orphanFixes.json`);
